name: Mirror AFFiNE to GHCR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone AFFiNE manually
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/toeverything/AFFiNE.git affine
          cd affine
          git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to your GHCR
        uses: docker/build-push-action@v5
        with:
          context: affine
          file: affine/.docker/selfhost/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/affine-self-hosted:latest
